# Generated by Django 5.2.16 on 2026-07-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(default=0, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=0, verbose_name='Stock mínimo'),
        ),
    ]
