# Generated by Django 5.2.16 on 2026-08-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen_alter_producto_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comision',
            field=models.IntegerField(default=0, help_text='Monto que gana el vendedor por vender una unidad de este producto', verbose_name='Comisión por unidad'),
        ),
    ]
