# Generated by Django 5.2.16 on 2026-08-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_combo',
            field=models.BooleanField(default=False, help_text='Si es True, este producto es un conjunto de otros productos y al venderse descuenta el inventario de sus componentes.', verbose_name='Es combo'),
        ),
        migrations.CreateModel(
            name='ComboComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='productos.producto', verbose_name='Combo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combos', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Componente de combo',
                'verbose_name_plural': 'Componentes de combo',
                'ordering': ['id'],
            },
        ),
    ]
