# Generated by Django 5.2.16 on 2026-09-05 00:00

from django.db import migrations


def asignar_orden(apps, schema_editor):
    Categoria = apps.get_model('productos', 'Categoria')
    for i, cat in enumerate(
        Categoria.objects.all().order_by('orden', 'nombre'), start=1
    ):
        cat.orden = i
        cat.save(update_fields=['orden'])


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_categoria_orden'),
    ]

    operations = [
        migrations.RunPython(asignar_orden, migrations.RunPython.noop),
    ]