# Generated by Django 5.2.16 on 2026-08-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='perm_caja',
            field=models.BooleanField(default=False, help_text='Apertura, cierre y egresos de caja.', verbose_name='Caja'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_cambiar_precio',
            field=models.BooleanField(default=False, help_text='Modificar el precio de los productos al vender.', verbose_name='Cambiar precios'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_cancelar_pedido',
            field=models.BooleanField(default=False, help_text='Cancelar pedidos abiertos.', verbose_name='Cancelar pedidos'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_configuracion',
            field=models.BooleanField(default=False, help_text='Editar la configuración del sistema.', verbose_name='Configuración'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_cortesia',
            field=models.BooleanField(default=False, help_text='Marcar productos o ventas completas como cortesía (gratis).', verbose_name='Dar cortesías'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_descuento',
            field=models.BooleanField(default=False, help_text='Aplicar descuentos manuales al pedido.', verbose_name='Aplicar descuentos'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_facturar',
            field=models.BooleanField(default=True, help_text='Abrir pedidos, agregar productos y cobrar ventas.', verbose_name='Facturar y cobrar'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_inventario',
            field=models.BooleanField(default=False, help_text='Registrar movimientos y consumo interno.', verbose_name='Gestionar inventario'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_productos',
            field=models.BooleanField(default=False, help_text='Crear, editar y eliminar productos, categorías y unidades.', verbose_name='Gestionar productos'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_reportes',
            field=models.BooleanField(default=False, help_text='Acceder a reportes y exportaciones.', verbose_name='Ver reportes'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='perm_trasladar_mesas',
            field=models.BooleanField(default=False, help_text='Mover pedidos de una mesa a otra.', verbose_name='Trasladar mesas'),
        ),
    ]
