# Generated by Django 5.2.16 on 2026-08-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_vendedor_perm_caja_vendedor_perm_cambiar_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='perm_ver_totales_caja',
            field=models.BooleanField(default=False, help_text='Ver el dinero esperado y los totales al cerrar la caja. Sin este permiso, puede cerrar la caja pero no verá los montos.', verbose_name='Ver totales de caja'),
        ),
    ]
