# Generated by Django 5.2.16 on 2026-08-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_vendedor_perm_ver_totales_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='perm_modificar_otros_pedidos',
            field=models.BooleanField(default=False, help_text='Permite operar mesas/pedidos de otros vendedores. Sin este permiso, cada vendedor solo maneja sus propias mesas.', verbose_name='Modificar mesas de otros'),
        ),
    ]
