# Generated by Django 5.2.16 on 2026-08-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_vendedor_perm_modificar_otros_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='perm_ver_facturas',
            field=models.BooleanField(default=True, help_text='Consultar y ver el detalle de las facturas emitidas. Independiente de poder facturar/cobrar.', verbose_name='Ver facturas'),
        ),
    ]
