# Generated by Django 5.2.16 on 2026-08-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_vendedor_perm_ver_facturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='es_receptor_pedidos',
            field=models.BooleanField(default=False, help_text='Recibe notificaciones en tiempo real de los pedidos enviados a caja desde las mesas.', verbose_name='Receptor de pedidos'),
        ),
    ]
