# Generated by Django 5.2.16 on 2026-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_vendedor_es_receptor_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='tour_completado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya completó el recorrido de capacitación.', verbose_name='Tour completado'),
        ),
    ]
