# Generated by Django 5.2.17 on 2026-09-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_add_tour_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='perm_eliminar_productos',
            field=models.BooleanField(default=False, help_text='Permite eliminar productos de un pedido de mesa, incluso si fue agregado por otro vendedor. Sin este permiso, un vendedor solo puede reducir la cantidad de los productos que agregó a su propia mesa.', verbose_name='Eliminar productos de las mesas'),
        ),
    ]