# Generated by Django 5.2.16 on 2026-07-08 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Número de mesa')),
                ('estado', models.CharField(choices=[('libre', '🟢 Libre'), ('activo', '🟡 Pedido activo'), ('parcial', '🟠 Pago parcial'), ('pagada', '🔵 Pagada'), ('cerrada', '🔴 Cerrada')], db_index=True, default='libre', max_length=10, verbose_name='Estado')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle del pedido',
                'verbose_name_plural': 'Detalles del pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo pendiente')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('cerrado', 'Cerrado')], db_index=True, default='activo', max_length=10, verbose_name='Estado')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mesas.mesa', verbose_name='Mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.vendedor', verbose_name='Mesero')),
                ('productos', models.ManyToManyField(related_name='pedidos', through='mesas.DetallePedido', to='productos.producto', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mesas.pedido', verbose_name='Pedido'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='mesas_pedid_estado_9fdc9c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['mesa', 'estado'], name='mesas_pedid_mesa_id_72be44_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['mesero'], name='mesas_pedid_mesero__3e62f5_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido', 'producto'], name='mesas_detal_pedido__f0e168_idx'),
        ),
    ]
