# Generated by Django 5.2.16 on 2026-07-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='es_cortesia',
            field=models.BooleanField(default=False, verbose_name='Cortesía'),
        ),
    ]
