# Generated by Django 5.2.16 on 2026-08-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_detallepedido_es_cortesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión'),
        ),
    ]
