# Generated by Django 5.2.16 on 2026-08-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_detallepedido_comision'),
        ('usuarios', '0006_vendedor_es_receptor_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mesas.mesa', verbose_name='Mesa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mesas.pedido', verbose_name='Pedido')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_enviadas', to='usuarios.vendedor', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de pedido',
                'verbose_name_plural': 'Solicitudes de pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='mesas.solicitudpedido', verbose_name='Solicitud enviada'),
        ),
    ]
