# Generated by Django 5.2.16 on 2026-09-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0004_solicitudpedido_detallepedido_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sesion_inicio',
            field=models.DateTimeField(blank=True, help_text='Última vez que el mesero entró a la mesa; Solicitar en caja solo envía productos desde esta fecha.', null=True, verbose_name='Inicio de sesión'),
        ),
    ]
