# Generated by Django 5.2.16 on 2026-07-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='soporte',
            field=models.FileField(blank=True, null=True, upload_to='egresos/', verbose_name='Archivo de soporte'),
        ),
    ]
