# Generated by Django 5.2.16 on 2026-07-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_egreso_soporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de egreso',
                'verbose_name_plural': 'Categorías de egresos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='egreso',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='caja.categoriaegreso', verbose_name='Categoría'),
        ),
    ]
