# Generated by Django 5.2.16 on 2026-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_categoriaegreso_egreso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
