# Generated by Django 5.2.16 on 2026-07-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_egreso_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperturacaja',
            name='monto_inicial',
        ),
    ]
