# Generated by Django 5.2.16 on 2026-07-31 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_remove_aperturacaja_monto_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cierre')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto inicial')),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas en efectivo')),
                ('total_ventas_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas por transferencia')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total ventas')),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total egresos')),
                ('total_egresos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Egresos en efectivo')),
                ('total_egresos_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Egresos por transferencia')),
                ('dinero_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dinero esperado')),
                ('efectivo_conteo', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo físico contado al cerrar la caja', max_digits=12, verbose_name='Efectivo contado')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='caja.aperturacaja', verbose_name='Caja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cierre de caja',
                'verbose_name_plural': 'Cierres de caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
    ]
