# Generated by Django 5.2.16 on 2026-07-31 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_cierrecaja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CierreCaja',
        ),
    ]
