# Generated by Django 5.2.16 on 2026-08-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_cierrecaja_total_comisiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='comisiones_detalle',
            field=models.JSONField(blank=True, default=list, verbose_name='Detalle de comisiones por vendedor'),
        ),
    ]
