# Generated by Django 5.2.16 on 2026-08-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='El Choli', max_length=100, verbose_name='Nombre de la empresa')),
                ('logo', models.ImageField(blank=True, help_text='Imagen que se muestra junto al nombre en el navbar y el login.', null=True, upload_to='logos/', verbose_name='Logo')),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
