# Generated by Django 5.2.16 on 2026-08-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='qr_consignacion',
            field=models.ImageField(blank=True, help_text='Código QR que se muestra al cobrar con transferencia para que el cliente consigne.', null=True, upload_to='qrs/', verbose_name='QR de consignación'),
        ),
    ]
