# Generated by Django 5.2.16 on 2026-07-08 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, help_text='Número consecutivo de factura', unique=True, verbose_name='Número de factura')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], db_index=True, max_length=20, verbose_name='Método de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('valor_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor recibido')),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cambio')),
                ('es_parcial', models.BooleanField(default=False, verbose_name='Pago parcial')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo pendiente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='mesas.mesa', verbose_name='Mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='usuarios.vendedor', verbose_name='Mesero')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='mesas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], db_index=True, max_length=20, verbose_name='Método')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('valor_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor recibido')),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.factura', verbose_name='Factura')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='mesas.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero'], name='ventas_fact_numero_fa0c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['metodo_pago'], name='ventas_fact_metodo__0efbce_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['created_at'], name='ventas_fact_created_97e2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['mesero'], name='ventas_fact_mesero__ccb753_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['mesa'], name='ventas_fact_mesa_id_625487_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo'], name='ventas_pago_metodo_d3c4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['factura'], name='ventas_pago_factura_ac094e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['created_at'], name='ventas_pago_created_f185e4_idx'),
        ),
    ]
