# Generated by Django 5.2.16 on 2026-07-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cortesia', 'Cortesía')], db_index=True, max_length=20, verbose_name='Método de pago'),
        ),
    ]
