# Generated by Django 5.2.16 on 2026-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_factura_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cortesia', 'Cortesía')], db_index=True, max_length=20, verbose_name='Método'),
        ),
    ]
