# Generated by Django 5.2.16 on 2026-07-08 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('venta', 'Venta')], db_index=True, max_length=10, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock anterior')),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock nuevo')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='inventario__tipo_b85d84_idx'), models.Index(fields=['producto', 'created_at'], name='inventario__product_4a6b02_idx')],
            },
        ),
    ]
