# Generated by Django 5.2.16 on 2026-07-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_consumointerno'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumointerno',
            name='empleado_nombre',
        ),
        migrations.AddField(
            model_name='consumointerno',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_internos', to='usuarios.vendedor', verbose_name='Empleado'),
        ),
    ]
